### ISSUE TITLE
test.py error 

### ISSUE THREAD

**Issue by FyyStudy** [jihoonerd/Robust-Motion-In-betweening#13]
When run python test.py, a error as following:
Traceback (most recent call last):
  File "/data1/fyy/Robust-Motion-In-betweening-main/test.py", line 223, in <module>
    test()
  File "/data1/fyy/Robust-Motion-In-betweening-main/test.py", line 48, in test
    lafan_dataset_test = LAFAN1Dataset(lafan_path=config['data']['data_dir'], processed_data_dir=config['test']['processed_data_dir'], train=False, device=device, window=window, training_frames=training_frames)
TypeError: LAFAN1Dataset.__init__() got an unexpected keyword argument 'training_frames'

**Comment by wang-zm18** [comment]
How did you solve it?  Just delete "training_frames=training_frames"?  The initialization of  LAFAN1Dataset indeed has no parameters named "training_frames". Thank you in advance!
