### ISSUE TITLE
the link of weights is not valid

### ISSUE THREAD

**Issue by icech** [jihoonerd/Robust-Motion-In-betweening#3]
1. the link of weights is not valid
2. can you add the config for lafan1

Waiting for help!

**Comment by jihoonerd** [comment]
Sorry for your inconvenience. I notice that the training weight link has been expired. You should retrain the model. I remember it took 7~8 hours to reproduce the demo. And I updated config to be compatible with LAFAN.

**Comment by icech** [comment]
Thank you very much!

**Comment by icech** [comment]
@jihoonerd  I have retarined the model using the new config（except the test windows should be set as 51 instead of 50）but to find the result is not same as the result in paper.  Do you have time to help find the reason or give some suggestion?

The log of run_benchmark.py is following: 
Predicting Frames:  40
MODELS LOADED WITH SAVED WEIGHTS
l2p: 2.2067885443001676
l2q: 4.469069480895996
npss: 0.2922711670398712

**Comment by jihoonerd** [comment]
Regarding this, I am not sure about it. I also tried various settings and managed to achieve a reported 30-frame score, but not on 40 frame setting. One probable reason would be curriculum learning. This implementation does not include curriculum learning, which is used in original paper.

**Comment by icech** [comment]
@jihoonerd The 40 frames setting is in the config_base.yaml（https://github.com/jihoonerd/Robust-Motion-In-betweening/blob/main/config/config_base.yaml）which was updated by you yeasterday. I didn't modify it.  Can I reproduce the 30-frame score by modifying the training_frames from 40 to 30?   Please help check the setting in config_base.yaml,  thx!

**Comment by jihoonerd** [comment]
@icech I reproduced the 30-frame setting with modified version of this paper as a part of my paper, not this one. It is not an easy task to completely reproduce other's paper, especially in graphics work like this. I recommend you to contact original author if you need exact results.

**Comment by icech** [comment]
@jihoonerd  I see.  Thanks for your kind reply!

**Comment by wang-zm18** [comment]
@icech  Did you reproduce the similar results compared to that in the paper? Thank you in advance!
