### ISSUE TITLE
No module named 'pymo.parsers

### ISSUE THREAD

**Issue by Cicistawberry** [jihoonerd/Robust-Motion-In-betweening#7]
When I run test.py, I met an issue "No module named 'pymo.parsers'".
But I already install pymo.

**Comment by jihoonerd** [comment]
I guess you might install pymo by `pip install pymo`. But this is a different module than I used in this repo. In this case, please read installation guide in README.md

**Comment by jihoonerd** [comment]
@Cicistawberry Oh it was my base 😓 . I will remove pymo in requirements.txt soon. Thanks for finding the error!
